/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 .\public\Models\eames.gltf -k -K 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Eames({opacity, ...props}) {
  const { nodes, materials } = useGLTF('./Models/eames.gltf')
  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <mesh name="Object_4" geometry={nodes.Object_4.geometry}>
          <meshStandardMaterial
            {...materials['01_-_Default']}
            transparent
            opacity={opacity}
          />
        </mesh>
      </group>
    </group>
  )
}

useGLTF.preload('./Models//eames.gltf')
