/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 .\public\Models\nordic_table.glb -K -k 
Author: Project Everything (https://sketchfab.com/projecteverything)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/nordic-table-6270118bb9524c06b1a984616f381bc1
Title: Nordic Table
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { fadeOnBeforeCompile } from '../utils/fadeMaterial';
import { useFrame } from '@react-three/fiber';

export function NordicTable({ sceneOpacity, ...props }) {
  const { nodes, materials } = useGLTF('./Models/nordicTable.gltf')

  const materialRef = useRef();

  useFrame(() => {
    materialRef.current.opacity = sceneOpacity.current;
  });

  return (
    <group {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="cdddeab993b741dbb9b5e46b3bb611c1fbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode">
              <group name="Furniture_Table_1" position={[0, 0.49, 81.84]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="Furniture_Table_1_M_Furniture_Table_1_0" geometry={nodes.Furniture_Table_1_M_Furniture_Table_1_0.geometry}>
                  <meshStandardMaterial
                    ref={materialRef}
                    onBeforeCompile={fadeOnBeforeCompile}
                    envMapIntensity={2}
                    transparent
                  />
                </mesh>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./Models/nordic_table.glb')
