/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 .\public\models\PaperPlane.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function PaperPlane(props) {
  const { nodes, materials } = useGLTF('./Models/PaperPlane.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.group1111588455.geometry} material={materials.mat21} />
    </group>
  )
}

useGLTF.preload('./Models/PaperPlane.glb')
