/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 .\public\Models\tablecoffe.gltf -K -k 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { fadeOnBeforeCompile } from '../utils/fadeMaterial';
import { useFrame } from '@react-three/fiber';

export function Tablecoffe({ sceneOpacity, ...props }) {
  const { nodes, materials } = useGLTF('./Models/tablecoffe.gltf')

  const materialRef = useRef();

  useFrame(() => {
    materialRef.current.opacity = sceneOpacity.current;
  });

  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <group name="Object_4" position={[-0.02, 1.235, 0]}>
          <mesh name="Object_0" geometry={nodes.Object_0.geometry}>
            <meshStandardMaterial
              ref={materialRef}
              onBeforeCompile={fadeOnBeforeCompile}
              envMapIntensity={2}
              transparent
            />
          </mesh>
          <mesh name="Object_0_1" geometry={nodes.Object_0_1.geometry}>
            <meshStandardMaterial
              ref={materialRef}
              onBeforeCompile={fadeOnBeforeCompile}
              envMapIntensity={2}
              transparent
            />
          </mesh>
          <mesh name="Object_0_2" geometry={nodes.Object_0_2.geometry}>
            <meshStandardMaterial
              ref={materialRef}
              onBeforeCompile={fadeOnBeforeCompile}
              envMapIntensity={2}
              transparent
            />
          </mesh>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./Models/tablecoffe.gltf')
