/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 .\public\Models\van.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Van(props) {
  const { nodes, materials } = useGLTF('/Models/van.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0, 2.748]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes['Tyre_and_Rims_-_Mid-Poly_|_Painted001_Stainless_Steel_0'].geometry} material={materials.Stainless_Steel} />
        <mesh geometry={nodes['Tyre_and_Rims_-_Mid-Poly_|_Painted001_Stainless_Steel_0_1'].geometry} material={materials.Rim_Tyre} />
        <mesh geometry={nodes['Tyre_and_Rims_-_Mid-Poly_|_Painted001_Stainless_Steel_0_2'].geometry} material={materials['Material.004']} />
      </group>
      <group position={[0, 0, -0.084]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes['Tyre_and_Rims_-_Mid-Poly_|_Painted002_Material004_0'].geometry} material={materials['Material.004']} />
        <mesh geometry={nodes['Tyre_and_Rims_-_Mid-Poly_|_Painted002_Material004_0_1'].geometry} material={materials.Rim_Tyre} />
        <mesh geometry={nodes['Tyre_and_Rims_-_Mid-Poly_|_Painted002_Material004_0_2'].geometry} material={materials.Stainless_Steel} />
      </group>
      <group position={[0, 0.673, 2.147]} rotation={[-0.332, 0, 0]}>
        <mesh geometry={nodes['3d-model001_Iron_brushed_0'].geometry} material={materials.Iron_brushed} />
        <mesh geometry={nodes['3d-model001_Iron_brushed_0_1'].geometry} material={materials['Material.014']} />
        <mesh geometry={nodes['3d-model001_Iron_brushed_0_2'].geometry} material={materials.cajuela} />
        <mesh geometry={nodes['3d-model001_Iron_brushed_0_3'].geometry} material={materials.cofre} />
        <mesh geometry={nodes['3d-model001_Iron_brushed_0_4'].geometry} material={materials['Material.007']} />
        <mesh geometry={nodes['3d-model001_Iron_brushed_0_5'].geometry} material={materials['Material.001']} />
        <mesh geometry={nodes['3d-model001_Iron_brushed_0_6'].geometry} material={materials['Material.006']} />
        <mesh geometry={nodes['3d-model001_Iron_brushed_0_7'].geometry} material={materials['Material.009']} />
        <mesh geometry={nodes['3d-model001_Iron_brushed_0_8'].geometry} material={materials.puertas} />
        <mesh geometry={nodes['3d-model001_Iron_brushed_0_9'].geometry} material={materials.puertas_tras} />
        <mesh geometry={nodes['3d-model001_Iron_brushed_0_10'].geometry} material={materials.cristlaatixq} />
        <mesh geometry={nodes['3d-model001_Iron_brushed_0_11'].geometry} material={materials.critastras} />
        <mesh geometry={nodes['3d-model001_Iron_brushed_0_12'].geometry} material={materials['Material.002']} />
        <mesh geometry={nodes['3d-model001_Iron_brushed_0_13'].geometry} material={materials.crist_der} />
        <mesh geometry={nodes['3d-model001_Iron_brushed_0_14'].geometry} material={materials.Cube__0} />
        <mesh geometry={nodes['3d-model001_Iron_brushed_0_15'].geometry} material={materials['Material.008']} />
        <mesh geometry={nodes['3d-model001_Iron_brushed_0_16'].geometry} material={materials['Material.010']} />
        <mesh geometry={nodes['3d-model001_Iron_brushed_0_17'].geometry} material={materials['Material.013']} />
      </group>
    </group>
  )
}

useGLTF.preload('/Models/van.gltf')
